### PR TITLE
feature/set-default-type-from-env-var

### PR DESCRIPTION
**Pull request by barakbd**
Still a useful tool :)

### CODE REVIEW

**Comment by KensoDev** [comment]
Thank you for this contribution

**Comment by barakbd** [comment]
Can you build/publish a new tag please?
I don't believe I have permissions

**Comment by KensoDev** [comment]
The build is failing. Most likely a lint issue.
Can you please verify the build is working properly locally? I can then
publish a new version.

Sincerely,
Avi Zurel

http://avi.io

**Comment by barakbd** [comment]
Do you use `GOPATH` instead of `go.mod` so package versions are not defined and so you always build off the latest and greatest?

**Pull request merged**
